#!/bin/bash
CURDIR=${PWD}

main()
{
	cd ${HOME}
	git clone https://github.com/crits/crits.git
	cd ${CURDIR}
	cp ${CURDIR}/bootstrap ${HOME}/crits/script/bootstrap
	cp ${CURDIR}/server ${HOME}/crits/script/server
	cp ${CURDIR}/stable_requirements.txt ${HOME}/crits/stable_requirements.txt
	cd ${HOME}/crits
	./script/bootstrap
	mv ${HOME}/crits /data/crits
	cd ${CURDIR}
	
}

main
