#!/bin/bash
CURDIR=${PWD}

main()
{
	cd /data
	sudo apt install git
	git clone https://github.com/crits/crits.git
	cd ${CURDIR}
	cp ${CURDIR}/bootstrap /data/crits/script/bootstrap
	cp ${CURDIR}/server /data/crits/script/server
	cp ${CURDIR}/stable_requirements.txt /data/crits/stable_requirements.txt
	cd /data/crits
	./script/bootstrap
	cd ${CURDIR}
}

main
